# Generated by Django 2.2.1 on 2019-07-23 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orginfo',
            name='category',
            field=models.CharField(choices=[('pxjg', '培训机构'), ('gx', '高校'), ('gr', '个人')], max_length=10, verbose_name='机构类别'),
        ),
        migrations.AlterField(
            model_name='orginfo',
            name='image',
            field=models.ImageField(max_length=1000, upload_to='orgs/', verbose_name='机构封面'),
        ),
        migrations.AlterField(
            model_name='teacherinfo',
            name='image',
            field=models.ImageField(max_length=1000, upload_to='teacher/', verbose_name='讲师头像'),
        ),
    ]
