# Generated by Django 2.2.1 on 2019-08-07 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverifycode',
            name='send_type',
            field=models.IntegerField(choices=[('register', '注册'), ('forget', '忘记密码'), ('change', '修改密码')], verbose_name='验证码类型'),
        ),
    ]
