# Generated by Django 2.2.1 on 2019-08-11 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190807_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverifycode',
            name='send_type',
            field=models.IntegerField(choices=[('register', '注册'), ('forget', '忘记密码'), ('update_email', '修改邮箱')], verbose_name='验证码类型'),
        ),
    ]
