# Generated by Django 2.2.1 on 2019-08-13 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20190811_2320'),
    ]

    operations = [
        migrations.AddField(
            model_name='bannerinfo',
            name='index',
            field=models.IntegerField(default=100, verbose_name='顺序'),
        ),
        migrations.AddField(
            model_name='bannerinfo',
            name='title',
            field=models.CharField(default=1, max_length=100, verbose_name='标题'),
            preserve_default=False,
        ),
    ]
