# Generated by Django 2.2.1 on 2019-08-13 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0004_auto_20190810_1650'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermessage',
            old_name='message_man',
            new_name='user',
        ),
    ]
