# Generated by Django 2.2.1 on 2019-08-10 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_courseinfo_tag'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VidioInfo',
            new_name='VideoInfo',
        ),
    ]
